// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qcxshyngywihizzawsxo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFjeHNoeW5neXdpaGl6emF3c3hvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYwNTAxNDgsImV4cCI6MjA3MTYyNjE0OH0.8dbqLUePdP5aAfSQSaueFbtNKGB9jQ0L-TBsKBmacnw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});